# 更新服务器的地址，注意这是McVersioning的版本，结尾一般是current-version.txt
# 可以写成列表的形式来使用多个备用源
server: http://127.0.0.1:1800/current-version.txt

# 更新完是否自动退出，默认值false（默认不开启此选项）
# true: 更新完后会自动关闭窗口
# false: 更新完后需要点击“确定”对话框退出程序
# auto-exit: true

# 存储当前版本号的文件（一般无需修改此选项）
# 起始目录为程序所在目录
# version-file: mv-version.txt

# 显式指定“更新起始目录”，默认值是空字符串""（一般无需修改此选项）
# 实际文件更新的起始目录 = 工作目录 + base-path
# 1.如果base-path被设置为'.'可以强制指定当前工作目录为更新起始目录并禁用.minecraft目录搜索
# 2.如果base-path被设置为../，这样就可以更新工作目录的上级目录了
# 3.如果base-path被设置为.minecraft222/，这样所有文件就会被更新到.minecraft222里
# 如果此选项被注释或者为空字符串''，程序会自动寻找最近的.minecraft目录的父目录作为更新起始路径
# 如果此选项未被注释，则会禁用自动搜寻.minecraft的功能。
# base-path: ''

# 安静模式（默认不开启此选项）
# true: 程序启动后不显示窗口，会在后台静默检查文件更新，如果没有更新就直接启动Minecraft，
#       如果有更新再显示下载进度条窗口，此选项可以尽可能将更新助手的存在感降低（只在下载文件时显示窗口）
# false: 程序启动后每次都显示窗口，并在窗口中显示检查文件的进度和下载文件的进度，一切妥当后启动Minecraft
# 此选项仅仅当程序以图型界面模式启动时有效
# quiet-mode: true

# 更新时如果发生错误（尤其是网络原因）时，是否继续进入游戏，而不是使游戏崩溃（默认不开启此选项）
# true: 如果更新发生错误，继续启动Minecraft游戏
# false：如果更新发生错误，强制使Minecraft崩溃，停止启动过程
# 如果需要区分是更新问题还是游戏本身的问题，请查看游戏启动日志
# 此选项仅当程序以JavaAgent模式（非图形模式）启动时有效
# no-throwing: true

# 全局http连接超时（单位毫秒）
# http-connect-timeout: 3000

# 全局http读取超时（单位毫秒）
# http-read-timeout: 50000

# 全局http写入超时（单位毫秒）
# http-write-timeout: 3000

# 下载文件时使用的线程数，默认使用4线程
# download-threads: 4

# 是否禁用主题，如果更新时窗口出现无响应的问题，请尝试禁用主题
# disable-theme: false

# 出现网络问题时的重试次数
# retry-times: 3

# 窗口宽度
# window-width: 450

# 窗口高度
# window-height: 315